require('dotenv').config();
const express = require('express');
const axios = require('axios');
const path = require('path');
const app = express();
const port = process.env.PORT || 3001;

const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;

app.use(express.json());

// API Routes
const crypto = require('crypto');

app.post('/api/ttlock/token-direct', async (req, res) => {
    const { username, password } = req.body;

    if (!username || !password) {
        return res.status(400).json({ error: 'Username and password are required' });
    }

    try {
        // TTLock requires MD5 password in lowercase
        const md5Password = crypto.createHash('md5').update(password).digest('hex');

        const params = new URLSearchParams();
        params.append('client_id', CLIENT_ID);
        params.append('client_secret', CLIENT_SECRET);
        params.append('username', username);
        params.append('password', md5Password);
        params.append('date', Date.now()); // Added date parameter as it's often required

        const response = await axios.post('https://euopen.ttlock.com/oauth2/token', params, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });

        // If TTLock returns an error in the body even with 200 OK
        if (response.data.errcode && response.data.errcode !== 0) {
            return res.status(400).json({ error: response.data.description || response.data.errmsg });
        }

        res.json(response.data);
    } catch (error) {
        console.error('Error getting access token direct:', error.response ? error.response.data : error.message);
        const errorMessage = error.response?.data?.description || error.response?.data?.errmsg || 'Failed to connect to TTLock. Please check your credentials and try again.';
        res.status(500).json({ error: errorMessage });
    }
});

app.get('/api/ttlock/locks', async (req, res) => {
    const { accessToken } = req.query;

    if (!accessToken) {
        return res.status(400).json({ error: 'Access token is missing' });
    }

    try {
        const response = await axios.get('https://euopen.ttlock.com/v3/lock/list', {
            params: {
                clientId: CLIENT_ID,
                accessToken: accessToken,
                pageNo: 1,
                pageSize: 20,
                date: Date.now()
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error fetching locks:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to fetch locks' });
    }
});

app.get('/api/ttlock/lock', async (req, res) => {
    const { accessToken, lockId } = req.query;

    if (!accessToken || !lockId) {
        return res.status(400).json({ error: 'Access token or lock ID is missing' });
    }

    try {
        const response = await axios.get('https://euopen.ttlock.com/v3/lock/detail', {
            params: {
                clientId: CLIENT_ID,
                accessToken: accessToken,
                lockId: lockId,
                date: Date.now()
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error fetching lock details:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to fetch lock details' });
    }
});

app.get('/api/ttlock/passcodes', async (req, res) => {
    const { accessToken, lockId } = req.query;

    if (!accessToken || !lockId) {
        return res.status(400).json({ error: 'Access token or lock ID is missing' });
    }

    try {
        const response = await axios.get('https://euopen.ttlock.com/v3/passcode/list', {
            params: {
                clientId: CLIENT_ID,
                accessToken: accessToken,
                lockId: lockId,
                pageNo: 1,
                pageSize: 20,
                date: Date.now()
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error fetching passcodes:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to fetch passcodes' });
    }
});

app.post('/api/ttlock/passcode', async (req, res) => {
    const { accessToken, lockId, passcode, startDate, endDate } = req.body;

    if (!accessToken || !lockId || !passcode || !startDate || !endDate) {
        return res.status(400).json({ error: 'Missing required parameters' });
    }

    try {
        const params = new URLSearchParams();
        params.append('clientId', CLIENT_ID);
        params.append('accessToken', accessToken);
        params.append('lockId', lockId);
        params.append('passcode', passcode);
        params.append('passcodeAlias', 'Generated by App');
        params.append('startDate', startDate);
        params.append('endDate', endDate);
        params.append('date', Date.now());

        const response = await axios.post('https://euopen.ttlock.com/v3/passcode/add', params, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error adding passcode:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to add passcode' });
    }
});

app.post('/api/ttlock/passcode/delete', async (req, res) => {
    const { accessToken, lockId, passcodeId } = req.body;

    if (!accessToken || !lockId || !passcodeId) {
        return res.status(400).json({ error: 'Missing required parameters' });
    }

    try {
        const params = new URLSearchParams();
        params.append('clientId', CLIENT_ID);
        params.append('accessToken', accessToken);
        params.append('lockId', lockId);
        params.append('passcodeId', passcodeId);
        params.append('date', Date.now());

        const response = await axios.post('https://euopen.ttlock.com/v3/passcode/delete', params, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error deleting passcode:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to delete passcode' });
    }
});

app.get('/api/ttlock/records', async (req, res) => {
    const { accessToken, lockId } = req.query;

    if (!accessToken || !lockId) {
        return res.status(400).json({ error: 'Access token or lock ID is missing' });
    }

    try {
        const response = await axios.get('https://euopen.ttlock.com/v3/lock/record/list', {
            params: {
                clientId: CLIENT_ID,
                accessToken: accessToken,
                lockId: lockId,
                pageNo: 1,
                pageSize: 50, // Get more records
                date: Date.now()
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error fetching records:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to fetch records' });
    }
});

// Ekey Endpoints
app.get('/api/ttlock/ekeys', async (req, res) => {
    const { accessToken, lockId } = req.query;

    if (!accessToken || !lockId) {
        return res.status(400).json({ error: 'Access token or lock ID is missing' });
    }

    try {
        const response = await axios.get('https://euopen.ttlock.com/v3/lock/listKey', {
            params: {
                clientId: CLIENT_ID,
                accessToken: accessToken,
                lockId: lockId,
                pageNo: 1,
                pageSize: 100,
                date: Date.now()
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error fetching ekeys:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to fetch ekeys' });
    }
});

app.post('/api/ttlock/ekey/send', async (req, res) => {
    const { accessToken, lockId, receiverAccount, startDate, endDate, remarks } = req.body;

    if (!accessToken || !lockId || !receiverAccount || !startDate || !endDate) {
        return res.status(400).json({ error: 'Missing required parameters' });
    }

    try {
        const params = new URLSearchParams();
        params.append('clientId', CLIENT_ID);
        params.append('accessToken', accessToken);
        params.append('lockId', lockId);
        params.append('receiverAccount', receiverAccount);
        params.append('startDate', startDate);
        params.append('endDate', endDate);
        params.append('remarks', remarks || '');
        params.append('date', Date.now());

        const response = await axios.post('https://euopen.ttlock.com/v3/key/send', params, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error sending ekey:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to send ekey' });
    }
});

app.post('/api/ttlock/ekey/freeze', async (req, res) => {
    const { accessToken, keyId } = req.body;

    if (!accessToken || !keyId) {
        return res.status(400).json({ error: 'Missing required parameters' });
    }

    try {
        const params = new URLSearchParams();
        params.append('clientId', CLIENT_ID);
        params.append('accessToken', accessToken);
        params.append('keyId', keyId);
        params.append('date', Date.now());

        const response = await axios.post('https://euopen.ttlock.com/v3/key/freeze', params, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error freezing ekey:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to freeze ekey' });
    }
});

app.post('/api/ttlock/ekey/unfreeze', async (req, res) => {
    const { accessToken, keyId } = req.body;

    if (!accessToken || !keyId) {
        return res.status(400).json({ error: 'Missing required parameters' });
    }

    try {
        const params = new URLSearchParams();
        params.append('clientId', CLIENT_ID);
        params.append('accessToken', accessToken);
        params.append('keyId', keyId);
        params.append('date', Date.now());

        const response = await axios.post('https://euopen.ttlock.com/v3/key/unfreeze', params, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error unfreezing ekey:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to unfreeze ekey' });
    }
});

app.post('/api/ttlock/ekey/delete', async (req, res) => {
    const { accessToken, keyId } = req.body;

    if (!accessToken || !keyId) {
        return res.status(400).json({ error: 'Missing required parameters' });
    }

    try {
        const params = new URLSearchParams();
        params.append('clientId', CLIENT_ID);
        params.append('accessToken', accessToken);
        params.append('keyId', keyId);
        params.append('date', Date.now());

        const response = await axios.post('https://euopen.ttlock.com/v3/key/delete', params, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });

        res.json(response.data);
    } catch (error) {
        console.error('Error deleting ekey:', error.response ? error.response.data : error.message);
        res.status(500).json({ error: 'Failed to delete ekey' });
    }
});

// Handle TTLock callback (GET and POST)
app.all('/auth/ttlock/callback', (req, res) => {
    // If it's a browser request (likely GET), send index.html
    // If it's a validation request, index.html is also fine as it returns 200 OK
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Serve static files from the React app
app.use(express.static(path.join(__dirname, 'dist')));

// The "catchall" handler: for any request that doesn't
// match one above, send back React's index.html file.
app.get('/*', (req, res) => {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(port, () => {
    console.log(`Proxy server listening at http://localhost:${port}`);
});

module.exports = app;
